from pathlib import Path
from datetime import datetime

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


class ExecutiveReportGenerator:
    """
    Generates a professional executive PDF report.
    """

    def __init__(self):
        self.project_root = Path(__file__).resolve().parent.parent.parent
        self.output_dir = self.project_root / "reports"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_pdf_report(
        self,
        query: str,
        answer: str,
        evaluation: dict,
    ) -> Path:

        report_path = self.output_dir / "executive_report.pdf"

        doc = SimpleDocTemplate(
            str(report_path),
            pagesize=LETTER,
        )

        styles = getSampleStyleSheet()
        story = []

        story.append(
            Paragraph(
                "Enterprise Business Intelligence Report",
                styles["Title"],
            )
        )

        story.append(Spacer(1, 16))

        story.append(
            Paragraph(
                f"Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                styles["Normal"],
            )
        )

        story.append(Spacer(1, 16))

        self._add_section(
            story,
            styles,
            "Business Question",
            query,
        )

        self._add_section(
            story,
            styles,
            "Executive Answer",
            answer.replace("\n", "<br/>"),
        )

        evaluation_text = f"""
Retrieval Score: {evaluation.get("retrieval_score")}<br/>
Graph Usage Score: {evaluation.get("graph_usage_score")}<br/>
Evidence Coverage Score: {evaluation.get("evidence_coverage_score")}<br/>
Critic Confidence Score: {evaluation.get("critic_confidence_score")}<br/>
Overall Enterprise RAG Score: {evaluation.get("overall_enterprise_rag_score")}
"""

        self._add_section(
            story,
            styles,
            "Evaluation Dashboard",
            evaluation_text,
        )

        self._add_section(
            story,
            styles,
            "Generated By",
            "Enterprise AI Data Intelligence Platform",
        )

        doc.build(story)

        return report_path

    def _add_section(
        self,
        story,
        styles,
        title: str,
        body: str,
    ):
        story.append(Paragraph(title, styles["Heading2"]))
        story.append(Spacer(1, 8))
        story.append(Paragraph(body, styles["BodyText"]))
        story.append(Spacer(1, 16))


if __name__ == "__main__":

    generator = ExecutiveReportGenerator()

    sample_evaluation = {
        "retrieval_score": 1.0,
        "graph_usage_score": 1.0,
        "evidence_coverage_score": 1.0,
        "critic_confidence_score": 1.0,
        "overall_enterprise_rag_score": 1.0,
    }

    path = generator.generate_pdf_report(
        query="What happened in quarterly_report.txt?",
        answer="""
Revenue increased by 22%.
Customer satisfaction reached 95%.
The AI department launched four new automation projects.
The Marketing department expanded into three international markets.
""",
        evaluation=sample_evaluation,
    )

    print("\nExecutive PDF report created:")
    print(path)